require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-graphql
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/20210129142307_init_schema.rb"
    - "bin/*"

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Naming/PredicateName:
  Enabled: true
  Exclude:
    - "app/graphql/**/*"

Style/Send:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/*"
    - "lib/tasks/*"

Rails/DynamicFindBy:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/Output:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**/*"

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Focus:
  AutoCorrect: false

GraphQL/FieldDefinitions:
  EnforcedStyle: define_resolver_after_definition

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false
