inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/RaiseArgs:
  Enabled: false

# Let's discuss this one
# I'd like to go double quotes everywhere, but am open to discussion
# Style/StringLiterals:
#   EnforcedStyle: double_quotes
