inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/RaiseArgs:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/Send:
  Enabled: true

# Let's discuss this one
# I'd like to go double quotes everywhere, but am open to discussion
# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes
