require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/20210129142307_init_schema.rb"
    - "Gemfile"
    - "bin/*"

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Naming/PredicateName:
  Exclude:
    - "app/graphql/**/*"

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Send:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# Let's discuss this one
# I'd like to go double quotes everywhere, but am open to discussion
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/*"
    - "lib/tasks/*"

Rails/DynamicFindBy:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Focus:
  AutoCorrect: false

GraphQL/FieldDefinitions:
  EnforcedStyle: define_resolver_after_definition

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false
