inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Send:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# Let's discuss this one
# I'd like to go double quotes everywhere, but am open to discussion
# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes
