inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: trailing

Style/RaiseArgs:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# Let's discuss this one
# I'd like to go double quotes everywhere, but am open to discussion
# Style/StringLiterals:
#   EnforcedStyle: double_quotes
