:concurrency: 5
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>
:queues:
  - default
  - mailers
  - active_storage_purge
  - active_storage_analysis
  - action_mailbox_routing
  - action_mailbox_incineration
