:concurrency: 5
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 1) %>
:queues:
  - critical
  - default
  - mailers
  - active_storage_purge
  - active_storage_analysis
  - action_mailbox_routing
  - action_mailbox_incineration
:schedule:
  interview_reminder:
    cron: '0 * * * * *'   # Runs once per minute
    class: InterviewReminderJob
