:concurrency: 5
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 1) %>
:queues:
  - critical
  - default
  - mailers
  - active_storage_purge
  - active_storage_analysis
  - action_mailbox_routing
  - action_mailbox_incineration
:schedule:
  AgreementReminderJob:
    every: 10 minutes
  InterviewReminderJob:
    every: 10 minutes
  PostInterviewJob:
    every: 10 minutes
  PaymentRequestDueJob:
    every: 10 minutes
  ConsultationReminderJob:
    every: 10 minutes
  InterviewRequestReminderJob:
    every: 10 minutes
  InterviewRequestAutoDeclineJob:
    every: 10 minutes
  AccountDeleteJob:
    cron: "0 0 6 * * *" # Every day at 6 AM
