:concurrency: 5
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 1) %>
:queues:
  - critical
  - default
  - mailers
  - active_storage_purge
  - active_storage_analysis
  - action_mailbox_routing
  - action_mailbox_incineration
:schedule:
  AgreementReminderJob:
    every: 10 minutes
  InterviewReminderJob:
    every: 10 minutes
  PostInterviewJob:
    every: 10 minutes
  PaymentRequestDueJob:
    every: 10 minutes
  PaymentRequestReminderJob:
    every: 10 minutes
  ConsultationReminderJob:
    every: 10 minutes
  InterviewRequestReminderJob:
    every: 10 minutes
  # temp disabled based on: https://advisable.slack.com/archives/CT7JQ8RMX/p1652368647257499
  # InterviewRequestAutoDeclineJob:
  #   every: 10 minutes
  AccountDeleteJob:
    cron: "0 0 06 * * *" # Every day at 6 AM
  CaseStudyArticleRoundupJob:
    cron: "0 0 15 * * 1" # At 3pm on Monday
