name: Asana
on: [pull_request]
jobs:
  asana:
    runs-on: ubuntu-latest
    name: Do Asana Stuff
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
